version: "3.7"

services:

  nginx:
    image: overlay-nginx
    build:
      context: ./docker
    init: true
    restart: on-failure
    ports:
    - $PORT:443
    volumes:
    - .:/usr/share/nginx/html:cached,ro
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ssl_cert:/etc/ssl:delegated

volumes:
  ssl_cert: